### ISSUE TITLE
Fehler beim Kompilieren "Cannot find symbol"

### ISSUE THREAD

**Issue by DanielL99** [johan12345/vertretungsplan-server#1]
"Settings" wird als fehlerhafte(s) Variable/Symbol erkannt, da "Settings.java" nicht (mehr) exestiert und ruft Fehler in DBManager, GetVertretungsplanServlet, und ParseThread aus

**Comment by johan12345** [comment]
In der Klasse `Settings` sind Dinge wie der API-Key für Google Cloud Messaging und das Datenbank-Passwort gespeichert, darum sind die nicht im Git-Repository enthalten. Die musst du also selbst anlegen.

Bitte beachte, dass diese Version des Servers und die Version der App unter
https://github.com/johan12345/vertretungsplan
schon 1,5 Jahre alt sind und nicht mehr weiterentwickelt werden. Die aktuelle Version der App und des Servers ist nicht mehr Open Source, nur die Parser für die Vertretungspläne unter https://github.com/johan12345/substitution-schedule-parser sind als eigene Java-Bibliothek Open Source und werden dort weiterentwickelt.
